//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERError
    {
        public int idError { get; set; }
        public string messageError { get; set; }
        public string userError { get; set; }
        public System.DateTime dateError { get; set; }
        public string nameStoreProcedureError { get; set; }
    }
}
