//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEGlobalParameters
    {
        public decimal IGV { get; set; }
        public decimal percentageMinWholesalePrice { get; set; }
        public decimal percentageMinRetailPrice { get; set; }
        public string userUpdated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
    }
}
