//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEProductPriceAudit
    {
        public int idAuditPP { get; set; }
        public int idProduct { get; set; }
        public decimal purchasePrice { get; set; }
        public decimal wholesalePrice { get; set; }
        public decimal wholesaleMinPrice { get; set; }
        public decimal retailPrice { get; set; }
        public decimal retailMinPrice { get; set; }
        public Nullable<decimal> partPrice { get; set; }
    }
}
