//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEProduct
    {
        public int idProduct { get; set; }
        public int idCategory { get; set; }
        public int idMarca { get; set; }
        public string codeUnit { get; set; }
        public string name { get; set; }
        public bool divisible { get; set; }
        public string divisibleCodeUnit { get; set; }
        public Nullable<int> divisibleNumberParts { get; set; }
        public bool perishable { get; set; }
        public bool traceable { get; set; }
        public string barcodeType { get; set; }
        public bool active { get; set; }
        public string userCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string userUpdated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
    }
}
